repos:
  # General hooks for file cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Python code formatting with black
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]

  # Python linting with ruff (DISABLED)
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.2.2
  #   hooks:
  #     - id: ruff
  #       args: ["--config=pyproject.toml", "--fix"]

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        stages: [pre-commit]

  # Type checking with mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-pyyaml, types-requests]
  #       args: ["--ignore-missing-imports", "--check-untyped-defs", "--explicit-package-bases"]
  #       exclude: ^tests/

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "src/"]
        exclude: ^tests/

  # Poetry lock file check (commented out due to issues)
  # - repo: https://github.com/python-poetry/poetry
  #   rev: 1.7.1
  #   hooks:
  #     - id: poetry-check
  #     - id: poetry-lock
  #       args: ["--check"]

  # Run tests (excluding integration and config tests that may fail in CI)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: poetry run pytest -v --tb=short --ignore=tests/integration --ignore=tests/unit/test_config.py
        types: [python]
        pass_filenames: false
        always_run: true
